### PR TITLE
Fixed plugin not working in newer flow launcher versions (#1)

### LINKED ISSUE #1: Plugin crashes when trying to search for something
Error: 
```
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Users\xvanhunen\AppData\Roaming\FlowLauncher\Logs\1.16.2\2024-01-10.txt
2. copy below exception message

Flow Launcher version: 1.16.2
OS Version: 18363.752
IntPtr Length: 8
x64: True

Python Path: C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 01/10/2024 10:45:48
Exception:
System.MissingMethodException: Method not found: 'Void Flow.Launcher.Plugin.SharedCommands.SearchWeb.NewTabInBrowser(System.String, System.String)'.
   at Flow.Launcher.Plugin.CPPreference.Main.<>c__DisplayClass6_1.<Query>b__3(ActionContext e)
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 286
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Plugin seems to be calling the wrong function. Looking in the source code the `Void NewTabInBrowser(System.String, System.String)` function doesnt exists indeed.

The `void OpenInBrowserTab(args)` does, does it need to be using this function? 
[Source file that i looked in](https://github.com/Flow-Launcher/Flow.Launcher/blob/dev/Flow.Launcher.Plugin/SharedCommands/SearchWeb.cs)

### PR DESCRIPTION
**Pull request by jonesy-b-dev**
Fixes https://github.com/peterschussheim/CPPreference-flow-plugin/issues/1

* Updated Flow.Launcher.Plugin from 1.4.0 to 4.1.1

* Updated .NET version from coreapp3.1 to net7.0-windows

* Changed all NewTabInBrowser() functions to OpenInBrowserTab() to fix the issue

### CODE REVIEW

**Comment by peterschussheim** [comment]
Thank you sir, looks great!

**Comment by jonesy-b-dev** [comment]
Your welcome! Really wanted to use your plugin so had to take a shot in fixing it xD. Nice work to you too for creating this plugin.

**Comment by NoPlagiarism** [comment]
@peterschussheim 
Don't forget to release this hotfix

**Comment by peterschussheim** [comment]
@NoPlagiarism I will work on this today

**Pull request merged**
